name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Docker pull image 
      run: docker pull santhoshh27/cicd-pipeline:latest 
    - name: Delete old docker container
      run: sudo docker rm -f  cicd-pipeline-container || true
    - name: Run docker container
      run: sudo docker run -d -p 3000:3000 --name cicd-pipeline-container santhoshh27/cicd-pipeline:latest

    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
      
