name: Docker Image CI/CD

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t santhoshh27/cicd-pipeline:latest .
      
      - name: Push to Docker Hub
        run: docker push santhoshh27/cicd-pipeline:latest

  deploy:
    needs: build 
    runs-on: [aws-ec2]

    steps:
      - name: pull image from docker hub
        run: docker pull santhoshh27/cicd-pipeline:latest
      - name: Delete old container
        run: docker rm -f cicd-pipeline-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 -name cicd-pipeline-container santhoshh27/cicd-pipeline:latest
          
        
