name: Docker CI

on: 
  push:
    branches:
    -  main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-docker@v2

      - name: Build Docker Image
        run: docker build -t my-todo-app .

      - name: Run Docker container
        run: docker run my-todo-app npm run start


